<%@ page contentType="text/html; charset=gb2312"%>
</tr>
<table width="778" border="0" cellpadding="0" align="center"
	bgcolor="#E4EDFB">
	<tr>
		<td width="39.9"></td>
		<td bgcolor="#000000" width="700.2">
			
		</td>
		<td width="39.9"></td>
	</tr>
	<tr>
		<td hight="1">
			&nbsp;
		</td>
	</tr>
	<tr>
		<td></td>
		<td>
                                                <br><br><br><br><br><br><br><br><br><br>
			<p align="center">
				网上书店销售系统
				<!--TTelephone-->
				电话: 010-20000204
				<!--TEMail-->
                                                                <br>
				电子邮件:<A HREF='mailto:2751308258@qq.com'>
			    2751308258@qq.com</A>
				
				<br>
				<a>本站请使用IE6.0或以上版本 1024*768为最佳显示效果</a>
			</p>
		</td>
		<td></td>
	</tr>
</table>
</BODY>
</HTML>
